name: supervisor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  loading_animation_widget: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  file_picker: ^9.0.0
  path: ^1.9.0
  window_manager: ^0.4.3
  flutter_colorpicker: ^1.1.0
  dotted_line_flutter: ^0.1.6
  path_provider: ^2.1.5
  dropdown_search: ^6.0.1
  image: ^4.5.2
  desktop_updater: ^1.1.1
  carousel_slider: ^5.0.0
  timelines_plus: ^1.0.6
  font_awesome_flutter: ^10.8.0
  flutter_localizations:
    sdk: flutter
  calendar_date_picker2: ^2.0.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/statuses/
    - assets/fonts/
  

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic

        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic

        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
